services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - 5435:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://anshul:anshul@db:5432/database?sslmode=disable
      - JWT_SECRET=dchat_super_secret_key_2024_anshul
    ports:
      - 4000:4000
    depends_on:
      - db
    restart: on-failure
    volumes:
      - uploads:/anshul/uploads

volumes:
  pgdata:
  uploads:
